---
- hosts: WebServer 
  become: true  

  vars:
    httpd_port: 80  # Default port for httpd

  tasks:
    - name: Ensure httpd repositories are enabled
      yum:
        name: httpd
        state: present
        enablerepo: epel
        disable_gpg_check: yes  

    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Set httpd listen port (alternative)
      set_fact:
        modified_line: "{{ 'Listen ' + httpd_port }}"

    - name: Update httpd config with modified line
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        state: present
        regexp: "^Listen "
        line: "{{ modified_line }}"

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

